services:
  - type: web
    name: fotopeso-webhook-test
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
